var GAME_LEVELS = [
  ["                                                                                            x  ",
   "                                                                                            x  ",
   "                                                                                            x  ",
   "                                                                                            x  ",
   "                                                                                            x  ",
   "                                                                                            x  ",
   "                                                                   o       o                x  ",
   "                                                             o    xx      xx     o          x  ",
   "                                                   o o      xx                              x  ",
   "                                                                                            x  ",
   "                                                  xxxxx                                     x  ",
   "                                                                                 o          x  ",
   "  xx                                                     o o                                x  ",
   "  x                                                                                         x  ",
   "  x                           o                         xxxxx                               x  ",
   "  x                         xxxx                                                 o          x  ",
   "  x  @         //           x  x                  o                                         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx                       x  ",
   "                                             x   x                  x            *          x  ",
   "                                             x!!!x                  x!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "                                             x!!!x                  x!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "                                             xxxxx                  xxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                               ",
   "                                                                                               "],
  ["xxxxxx!!!!!!!!!!!!!!!!!!!     !!!!!!!xx!!xxxxxx                                                              x!x  ",
   "xxxxxxx!!!!!!!!!!!!!!!!!!!   !!!!!!!xxx!!xxxxxxxx                                                            x!x  ",
   "xxxxxxxx!!!!!!!!!!!!!!!!!!! !!!!!!!xxxx!!xxxxxxxxxx                                                          x!x  ",
   "xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx!!!!!!!!!!xx                                                         x!x  ",
   "xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxx!!xxx                                             o   o   o  x!x  ",
   "xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!xxx!     xxxxx!x                                                      //xx!x  ",
   "xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     xxxx!x                                     xxxxxxxxxxxxxxxxxxxx!!x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!     xxv                                     x!!!!!!!!!!!!!!!!!!!!!xx  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!                  o            o             vxxxxxxxxxxxxxxxxxxxxx   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!                 xx!!!!xxx!!!!xx               xxxxxxxxxxxxxxxxxx    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!                xxxx!!!!!xxxx                  xxxxxxxxxxxxxxx     ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxx                  xxxxxvx        xxx         xxxxxxxxxxxxxxx      ",
   "xxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxx!!!xxx         xxxx                    x x         xxxxxxxxxxxxxx       ",
   "xxxxxxxxxxxxxxxxxx!xxx          xxxxxxxxxxx!!xxx                                   x         xxxxxxxxxxxxx        ",
   "xxxxxxxxxxxxxxx  !!xx                       !!!x     o                             xx        xxxxxxxxxxxx         ",
   "x   xx                                       !!!x   xxx                            x         xxxxxxxxxxx          ",
   "                                            !!!!!    x                   x         x         xxxxxxxxxx           ",
   "              o                            !xxxx     x                   x         x         xxxxxxxx             ",
   "              xxxxxxxxx                   !xxxxx     x               x   x   xxxxxxxxx       xxxxxx               ",
   "             xxxxxxxxxxx!                 xxxxxx    xxx             xx   x   x               xx                   ",
   "     @      !xxxxxxxxxxx!!               xxxxxxx    !x             xxx   x   x               x                    ",
   "!   xxx    !!xxxxxxxxxxx!!!xxxx         xxxxxxxx     x            xxxx   xxxxx   xxxxxx      x                    ",
   "!!  x x!  !!!xxxxxxxxxxx!!!!!!xxx      xxxxxxxxx     xxxxxxxxx     xxx!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!!xx        x!!!!!!xx    x!!!!!!!!!!    xx!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!xx          xxxxxxx     x!!!!!!!xxv     xxxxxxxxxxxxxvxx!!!!!!!xx              !!!!!!",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!x                      xx!!!!!!xx                      xx!!!!!xx           !!!!!!!!!!",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!x          o          xx!!!!!!xx                        xxxxxxx        !!!!!!!!!!!!!!",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!xx        xxxxxxxxxxxxx!!!!!!xx                                    !!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                              !!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  x                                                                                              x            ",
   "  x                                                                                              x            ",
   "  x                                                                                              x            ",
   "  x                                                                                              x            ",
   "  x                                                                                              x            ",
   "  x                                                                                              x            ",
   "  x                                                                                              x            ",
   "  x                                                                                              x            ",
   "  x                                                                                              x            ",
   "  x                                                                                              x            ",
   "  x                o               oxxxxx         o                                              x            ",
   "  x                xxxxxx     xxxxxo     xxxxxxxxxxxxxx                                          x            ",
   "  x               x   o  xxxxx                                                                   x            ",
   "  x       x@     x    @     *    x     /     xo         ooooooooo                                x            ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                        ",
   "       !  o  !                                              x   x   x    x   x   x     x xxxxx x   x  x       ",
   "       x     x                                               x x   x  x  x   x   x     x   x   x x x  x       ",
   "       x= o  x            x                                   x   x    x x   x   x     x   x   x  xx  x       ",
   "       x     x                                                x    x  x  x   x   x  x  x   x   x   x          ",
   "       !  o  !            o                                   x     x      xx     x  x   xxxxx x   x  x       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx        *                                                             ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x/                //                 /x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
